spring:
  datasource:
    username: user
    password: pw
    url: jdbc:mariadb://localhost:3306/bweng_ws23
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
security:
  cors:
    allowed-origins: localhost:8080
    allowed-methods: GET, POST, PUT, OPTIONS, HEAD
server:
  port: 8081
