spring:
  datasource:
    username: user
    password: pw
    url: jdbc:mariadb://localhost:3306/bweng_ws23
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      max-file-size: 20MB
security:
  cors:
    allowed-origins: http://localhost:8080/
    allowed-methods: GET, POST, PUT, PATCH, OPTIONS, HEAD
  jwt:
    secret: Q9cXU3bgJFQC6xyPt2uh7UOreLhMAk
    issuer: bweng
server:
  port: 8081

minio:
  url: http://localhost
  port: 9000
  user: minioadmin
  password: minioadminpw
  bucket: files