###
POST http://localhost:8081/user/register
Content-Type: application/json

{
  "username": "admin1",
  "password": "test"
}

###
POST http://localhost:8081/user/token
Content-Type: application/json

{
  "username": "admin",
  "password": "test"
}

> {%
    client.global.set("auth_token", response.body.json.token);
%}

###
GET http://localhost:8081/movie

###
GET http://localhost:8081/room
Authorization: Bearer {{auth_token}}

###
GET http://localhost:8081/show

### User
POST http://localhost:8081/movie
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjM2Q0NzIzNi1lNGE2LTRkY2QtYWY1Yy1mZTIxNmU4MDM2MWUiLCJpc3MiOiJid2VuZyIsImV4cCI6MTcwMTg4NjY2OCwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJST0xFX0FETUlOIn0.HTnIvZz6d-E5h1NhCTtKsfL6RICc_yREmYSCDv9Zs-w

{
  "name": "Shrek 2",
  "durationMinutes": 15
}

### Admin
POST http://localhost:8081/movie
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjM2Q0NzIzNi1lNGE2LTRkY2QtYWY1Yy1mZTIxNmU4MDM2MWUiLCJpc3MiOiJid2VuZyIsImV4cCI6MTcwMTYyNzk0MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJST0xFX0FETUlOIn0.OeyZclQu6mMANpRml-Tc_DwnHkAtSasIgG7YeVFOl1U

{
  "name": "Shrek 2",
  "durationMinutes": 15
}

### Staff
POST http://localhost:8081/movie
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MTI3ODhjZi00OWYyLTQxY2UtYjYzZS1lYWUxNmNhYzhiNDIiLCJpc3MiOiJid2VuZyIsImV4cCI6MTcwMTg4NjYzMCwidXNlcm5hbWUiOiJzdGFmZiIsInJvbGUiOiJST0xFX1NUQUZGIn0.haT6RE3gu3w38iHYBF8y52CSmni6ozubQlkQMF5xfuA

{
  "name": "Shrek 2",
  "durationMinutes": 15
}

###
POST http://localhost:8081/room
Content-Type: application/json


{
  "name": "room3",
  "capacity": 500,
  "cleaningMinutes": 60
}


###
POST http://localhost:8081/show
Content-Type: application/json

{
  "startTime": "2023-11-27T15:00:00",
  "movieId": "2a27199f-6bc2-4a79-89e2-b538a10e30be",
  "roomId": "c38d5b4a-78fb-4d35-8f4c-b73ce4cf5a0a"
}

