###
POST http://localhost:8081/user/register
Content-Type: application/json

{
  "username": "admin",
  "password": "test"
}

###
POST http://localhost:8081/user/token
Content-Type: application/json

{
  "username": "admin",
  "password": "test"
}

> {%
    client.global.set("auth_token", response.body.json.token);
%}

###
GET http://localhost:8081/movie

###
GET http://localhost:8081/room
Authorization: Bearer {{auth_token}}

###
GET http://localhost:8081/show

### User
POST http://localhost:8081/movie
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNjQwYjAwOS1kZDU3LTRiM2YtYmZjYy1jNTMwZmU2MTY1NjYiLCJpc3MiOiJid2VuZyIsImV4cCI6MTcwMTYyMDQwOSwidXNlcm5hbWUiOiJ0ZXN0Iiwicm9sZSI6IlJPTEVfVVNFUiJ9.7luE4tO87fJ8spw4r77_hJcFgRonhvNShqyA2HsxI0M

{
  "name": "Shrek 2",
  "durationMinutes": 15
}

### Admin
POST http://localhost:8081/movie
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjM2Q0NzIzNi1lNGE2LTRkY2QtYWY1Yy1mZTIxNmU4MDM2MWUiLCJpc3MiOiJid2VuZyIsImV4cCI6MTcwMTYyMDQ0NSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJST0xFX0FETUlOIn0.qnN6hTQthj7a15ZSoUcrk4wDN-STOHRaeeet36Rl0f8

{
  "name": "Shrek 2",
  "durationMinutes": 15
}

### Staff
POST http://localhost:8081/movie
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MTI3ODhjZi00OWYyLTQxY2UtYjYzZS1lYWUxNmNhYzhiNDIiLCJpc3MiOiJid2VuZyIsImV4cCI6MTcwMTYyMDQyOCwidXNlcm5hbWUiOiJzdGFmZiIsInJvbGUiOiJST0xFX1NUQUZGIn0.VyRsMbBZEQw7w2rOnAzBuOYtT2fgNekzSmPxH5ZUMHI

{
  "name": "Shrek 2",
  "durationMinutes": 15
}

###
POST http://localhost:8081/room
Content-Type: application/json


{
  "name": "room3",
  "capacity": 500,
  "cleaningMinutes": 60
}


###
POST http://localhost:8081/show
Content-Type: application/json

{
  "startTime": "2023-11-27T15:00:00",
  "movieId": "2a27199f-6bc2-4a79-89e2-b538a10e30be",
  "roomId": "c38d5b4a-78fb-4d35-8f4c-b73ce4cf5a0a"
}

