###
GET http://localhost:8081/movies

###
GET http://localhost:8081/rooms

###
GET http://localhost:8081/shows

###
POST http://localhost:8081/movies
Content-Type: application/json

{
  "name": "Shrek 2",
  "durationMinutes": 15
}

###
POST http://localhost:8081/rooms
Content-Type: application/json

{
  "name": "room3",
  "capacity": 500,
  "cleaningMinutes": 60
}


###
POST http://localhost:8081/shows
Content-Type: application/json

{
  "startTime": "2023-11-27T15:00:00",
  "movieId": "2a27199f-6bc2-4a79-89e2-b538a10e30be",
  "roomId": "c38d5b4a-78fb-4d35-8f4c-b73ce4cf5a0a"
}